config/routes.rb
Rails.application.routes.draw do
  resources :micropost

  devise_for :users
    as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'
  get 'redirect_to_donate', to: 'donation#create_log', as: 'redirect_to_donate'

  post 'applause', to: 'applause#create', as: 'applause_create'
  post 'donation', to: 'donation#add_donation', as: 'add_donation'
  post 'treatment', to: 'treatment#add_treatment', as: 'add_treatment'
  
  post '/purchase' => 'orders#purchase_status'
  get "refund/:id", to: "orders#refund"

  get 'thankyou', to: 'home#thankyou', as: 'thankyou'
  get 'confirmation', to: 'home#confirmation', as: 'confirmation'
  # get 'calendar', to: 'home#calendar', as: 'calendar'

  resources :issue, only: [:create]

  get 'gift/:date', to: 'gift#show', as: 'gift_of'
  post 'gift_order', to: 'gift#order', as: 'gift_order'

  get 'admin_home', to: 'admin#home', as: 'admin_home'
  get 'admin_status_update', to: 'admin#status_update', as: 'status_update'
end

app/models/applause.rb
class Applause < ApplicationRecord
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/models/donation_log.rb
class DonationLog < ApplicationRecord
end

app/models/gift.rb
class Gift < ApplicationRecord
  has_one :substance
end

app/models/issue.rb
class Issue < ApplicationRecord
  validates :price, presence: true
  validates :price, numericality: { other_than: 0 }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  mount_uploader :image, ImageUploader
  enum status: { treatment: 0, suvivor: 1 }
end

app/models/micropost_log.rb
class MicropostLog < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  include OrderConcerns::Razorpay
  # belongs_to :product
  # belongs_to :user

  [:authorized, :captured, :refunded, :error].each do |scoped_key|
    scope scoped_key, -> { where('LOWER(status) = ?', scoped_key.to_s.downcase) }
  end

  class << self
    def process_razorpayment(params)
      issue = Issue.find(params[:product_id])
      razorpay_pmnt_obj = fetch_payment(params[:payment_id])
      status = fetch_payment(params[:payment_id]).status
      if status == "authorized"
        razorpay_pmnt_obj.capture({amount: issue.price * 100})
        razorpay_pmnt_obj = fetch_payment(params[:payment_id])
        params.merge!({status: razorpay_pmnt_obj.status, price: issue.price * 100})
        Order.create(params)
      else
        raise StandardError, "UNable to capture payment"
      end
    end

    def process_refund(payment_id)
      fetch_payment(payment_id).refund
      record = Order.find_by_payment_id(payment_id)
      record.update_attributes(status: fetch_payment(payment_id).status)
      return record
    end

    def filter(params)
      scope = params[:status] ? Order.send(params[:status]) : Order.authorized
      return scope
    end
  end
end

app/models/request.rb
class Request < ApplicationRecord
  validates :name, presence: true
end

app/models/request_gift_log.rb
class RequestGiftLog < ApplicationRecord
  def self.create_log(request_id, gift_id, status=0)
    RequestGiftLog.create(request_id: request_id, gift_id: gift_id, status: status)
  end

  def self.status_update(log)
    if log.status == 0
      log.update(status: 1)
    else
      log.update(status: 0)
    end
    
  end
end

app/models/substance.rb
class Substance < ApplicationRecord
  belongs_to :gift
end

app/models/treatment.rb
class Treatment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/applause_helper.rb
module ApplauseHelper
end

app/helpers/donation_helper.rb
module DonationHelper
end

app/helpers/gift_helper.rb
module GiftHelper
  def requested?(gift)
    return !!RequestGiftLog.find_by(gift_id: gift.id)
  end

  def gift_name(gift_id)
    Gift.find(gift_id).substance.name
  end
  def gift_price(gift_id)
    Gift.find(gift_id).substance.price
  end
  def gift_date(gift_id)
    Gift.find(gift_id).date
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issue_helper.rb
module IssueHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <b>Current Requests</b>
      <table class="table">
        <tbody>
          <thead>
            <th>id</th>
            <td>amount</td>
            <td>Name</td>
            <td>timestamp</td>
          </thead>
          <% @requests.each do |request| %>
            <tr>
              <th><%= request.id %></th>
              <td><%= request.total %></td>
              <td><%= request.name %></td>
              <td><%= request.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
            </tr>
          <% end %>    
        </tbody>
      </table>
    </div>
    <div class="col-md-8">
      <b>Log</b>
      <table class="table">
        <tbody>
          <thead>
            <th>id</th>
            <td>Gift</td>
            <td>Day</td>
            <td>Price</td>
            <td>Request</td>
            <td>Status</td>
            <td>Change</td>
          </thead>
          <% @request_gift_log.each do |log| %>
            <tr>
              <th><%= log.id %></th>
              <td><%= gift_name(log.gift_id) %></td>
              <td><%= gift_date(log.gift_id).strftime('%Y/%m/%d') %></td>
              <td>Rs.<%= gift_price(log.gift_id) %></td>
              <td><%= log.request_id %></td>
              <td>
                <% if log.status == 0 %>
                  Pending
                <% elsif %>
                  Done
                <% end %>
              </td>
              <td><%= link_to 'Change', status_update_path(id: log.id) %></td>
            </tr>
          <% end %>    
        </tbody>
      </table>
    </div>
    </div>
  </div>
</div>

app/views/layouts/_contributebtn-fixed.html.erb
<button type="button" class="button1"data-toggle="modal" data-target="#contributeModal">
  Contribute now!
</button>


<div class="modal fade" id="contributeModal" tabindex="-1" role="dialog" aria-labelledby="contributeModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="contributeModalLabel">Thank you for your contributing</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>Type the amount of Rs. you donate</div><br>
        <button id="down-button">
          <i class="fas fa-minus-circle" aria-hidden="true"></i>
        </button>
        <button id="up-button">
          <i class="fas fa-plus-circle" aria-hidden="true"></i>
        </button>
        <div>
          <%= form_for(@issue, url: issue_index_path, remote: true, class: 'form-group inline') do |f| %>
            <%= f.number_field :price,class: 'form-control modal-price', id: 'price-field', min: '0' %>
            <br><br>
            <%= f.submit 'Confirm', class: 'button1' %>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
$('#price-field').val(0);
$('#up-button').on('click', function() {
  var target = $('#price-field').val();
  var result = parseInt(target) + 100;
  $('#price-field').val(result);
});
$('#down-button').on('click', function() {
  var target = $('#price-field').val();
  var result = parseInt(target) - 100;
  $('#price-field').val(result);
});
</script>

<style type="text/css">
.donate-description {
  width: 100%;
}
.modal-price {
  width: 50%;
  margin: auto;
  font-size: 24px;
}
#up-button {
  float: right;
  margin-right: 10px;
  font-size: 35px;
  background: none;
  border: 0;
}
#down-button {
  float: left;
  margin-left: 10px;
  font-size: 35px;
  background: none;
  border: 0;
}
</style>

app/views/layouts/_contributebtn.html.erb
<button type="button" class="button1"data-toggle="modal" data-target="#contributeModal">
  Contribute now
</button>


<div class="modal fade" id="contributeModal" tabindex="-1" role="dialog" aria-labelledby="contributeModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="contributeModalLabel">Thank you for your help</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          The donation system is in the HP of Indian Cancer Society. You are going to redirect to HP and find forms there. <br> <br>
          In "Purpose of donation", please check <b>Cancer Treatment</b>. Then you can contribute to it. <br> <br>
          <b>*You cannot contribute to the individual.</b>
          <br>
          <div>
            <%= image_tag 'donate-description.png', class: 'donate-description' %>
          </div>
        </div>
        <div style="text-align: center;">

          <%= link_to redirect_to_donate_path do %>
            <button class="button1-sm">OK</button>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<style type="text/css">
.donate-description {
  width: 100%;
}
</style>

app/views/layouts/_contributed-direct.html.erb
<div align="center">
  
<form action="/purchase" method="POST" id="price500">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_wCMDwGpNaYQL4u"

    data-amount="<%= "#{@issues.find(1).price}" %>"
    data-name="Contribute for patients"
    data-description="You can contribute directry."

    data-prefill.name="testname"
    data-theme.color="#F37254"
>
</script>
  <input type="hidden" value="<%= "#{@issues.find(1).id}" %>" name="product_id">
</form>


</div>

<style>
.razorpay-payment-button {
  background-color: #4CAF50;
  color: white;
  padding: 15px 20px;
  border: none;
  cursor: pointer;
  display: inline-block;
  text-align: center;
  margin-top: 20px;
  min-width: 222px;
}
.razorpay-payment-button:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19); 
}
</style>

<script>
  $('#price500 > .razorpay-payment-button:first').prop('value', 'Donate ₹500');
  $('#price1000 > .razorpay-payment-button:first').prop('value', 'Donate ₹1000');
  $('#price3000 > .razorpay-payment-button:first').prop('value', 'Donate ₹3000');
  $('#price5000 > .razorpay-payment-button:first').prop('value', 'Donate ₹5000');
</script>

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer class="page-footer font-small stylish-color-dark pt-4 mt-4" style="background-color: #3D4452;color: white;">

    <!--Footer Links-->
    <div class="container text-center text-md-left">
        <div class="row">

            <!--First column-->
            <div class="col-md-6">
                <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">About this site</h5>
                <p>
                    This site is a social crowdfunding made by The Indian Cancer Society - Cancer Cure Fund. This fund is aimed at poor patients who are unable to afford the initial costs of diagnosis and/or need help in covering certain part of their treatment costs.
                </p>
            </div>
            <!--/.First column-->

            <hr class="clearfix w-100 d-md-none">

            <!--Second column-->
            <div class="col-md-6 mx-auto">
                <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">For more details</h5>
                <div class="text-center">
                    <%= link_to image_tag('indian-cancer-society-logo.png'), 'http://www.indiancancersociety.org/default.aspx', class: 'big_logo' %>
                </div>
            </div>
            <!--/.Second column-->

            <hr class="clearfix w-100 d-md-none">

        </div>
    </div>

    <hr>
        <div class="text-center">
            74, Jerbai Wadia Road, Bhoiwada, Parel, Mumbai - 400 012 (INDIA)<br />
            <b>Tel:</b> +91-22-2413 9445 / 51 &nbsp;&nbsp;&nbsp; <b>E-mail:</b>
            <a href="mailto:info@indiancancersociety.org">info@indiancancersociety.org</a>
        </div>
    <hr>
        <div class="text-center">
            © Copyright. Indian Cancer Society. All rights reserved.
        </div>
<!--     <div class="footer-copyright py-3 text-center">
        
    </div> -->

</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= image_tag 'indian-cancer-society-logo.png', class: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'About us', 'http://www.indiancancersociety.org/about-ics/ics-profile.aspx', class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Contact us', 'http://www.indiancancersociety.org/contact-us/national-head-quarters.aspx', class: "nav-link" %>
      </li>
      <% if user_signed_in?  %>
        <li class="nav-item active">
          <%= link_to 'Create New Post', new_micropost_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_post-box.html.erb
<div class="col-sm-4 post-box-wrapper">
  <%= link_to micropost_path(micropost) do %>
    <div class="post-box">
      <div class="box-title">
        <b><%= micropost.title %></b>
      </div>
      <div class="box-thumb">
        <% if Rails.env == 'development' %>
          <%= image_tag "profile/profile#{micropost.id}.jpeg" %>
        <% end %>
        <% if micropost.image? %>
          <%= image_tag micropost.image_url(:thumb) %>
        <% end %>
      </div>
      <div class="box-content">
        <%= micropost.plain_content %>
      </div>
    </div>
  <% end %>
</div>


<style>
.post-box:hover {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}

.post-box {
  width: 90%;
  height:400px;
  margin:5px;
  padding:10px;
  background-color:white;
  color: black;
}

.subtitle {
  margin-top: 60px;
  margin-bottom: 12px;
}
.box-thumb img {
  margin-top: 5px;
  height: 180px;
  width: 90%;
  object-fit: cover;
  background-color: #ccc;
  border: 1px solid #ccc;
}
.box-content {
  width: 90%;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 5 !important;
  overflow: hidden;
  text-align: left;
  margin: 10px 0px;
  font-size: 14px !important;
}
.post-box-wrapper a {
  text-decoration: none;
}
.box-title {
  font-size: 20px;
  line-height: 1.2;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Donation for Cancer | Indian Cancer Society</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta  name="viewport" content="width=device-width">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113767013-2"></script>

    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-113767013-2');
    </script>


  </head>

  <body>
      <%= render 'layouts/header' %>
      <div id="wrap">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
  </body>
</html>

<style>
html,
body {
  height: 100%;
  font-family: 'Noto Sans',sans-serif;
  line-height: 1.9;
  background-color: #f3f4f7;
}
@media screen and ( max-width:479px )
{
  body {
    font-size: 14px;
  }
}

#wrap {
  min-height: 100%;
  height: auto;
  margin: 0 auto -60px;
  padding: 0 0 60px;
}
</style>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" id="modal-btn">
    How to contribute?
  </button>
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if day > Time.current.since(7.days) %>
                <%= link_to gift_of_path(day) do %>
                  <%= day.strftime('%-m/%-d') %>
                <% end %>
              <% else %>
                <%= day.strftime('%-m/%-d') %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">How to contribute?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

Thank you for your cooperation in raising funds.  <br><br>
Here you can support patients and their families with what you specified on the day you designated. <br>
First of all, please choose the day you want them to receive your support. You can support after 7 days from today. <br>
Next, please choose the items to support. You can not select what others already supported.
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<style>
  .current-month {
    background: white;
  }
@media screen and ( max-width:479px )
{
  .simple-calendar td {
      font-size: 10px;
      padding: 0px; 
      vertical-align: top;
      width: 12%; 
      border: 1px solid #ddd;
      border-top-color: #dddddd;
      border-top-style: solid;
      border-top-width: 1px;
      border-right-color: #dddddd;
      border-right-style: solid;
      border-right-width: 1px;
      border-bottom-color: #dddddd;
      border-bottom-style: solid;
      border-bottom-width: 1px;
      border-left-color: #dddddd;
      border-left-style: solid;
      border-left-width: 1px;
  }
  .simple-calendar .day {
      height: 60px;
  }
  .simple-calendar th {
      font-size: 10px;
      padding: 0px; 
  }
}
</style>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>