config/routes.rb
Rails.application.routes.draw do
  resources :micropost

  devise_for :users
    as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'
  get 'redirect_to_donate', to: 'donation#create_log', as: 'redirect_to_donate'

  post 'applause', to: 'applause#create', as: 'applause_create'
  post 'donation', to: 'donation#add_donation', as: 'add_donation'
  post 'treatment', to: 'treatment#add_treatment', as: 'add_treatment'
  
  post '/purchase' => 'orders#purchase_status'
  get "refund/:id", to: "orders#refund"

  get 'thankyou', to: 'home#thankyou', as: 'thankyou'
  get 'confirmation', to: 'home#confirmation', as: 'confirmation'
  # get 'calendar', to: 'home#calendar', as: 'calendar'

  resources :issue, only: [:create]

  get 'gift/:date', to: 'gift#show', as: 'gift_of'
  post 'gift_order', to: 'gift#order', as: 'gift_order'

  get 'admin_home', to: 'admin#home', as: 'admin_home'
  get 'admin_status_update', to: 'admin#status_update', as: 'status_update'
end

app/models/applause.rb
class Applause < ApplicationRecord
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/models/donation_log.rb
class DonationLog < ApplicationRecord
end

app/models/gift.rb
class Gift < ApplicationRecord
  has_one :substance
end

app/models/issue.rb
class Issue < ApplicationRecord
  validates :price, presence: true
  validates :price, numericality: { other_than: 0 }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  mount_uploader :image, ImageUploader
  enum status: { treatment: 0, suvivor: 1 }
end

app/models/micropost_log.rb
class MicropostLog < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  include OrderConcerns::Razorpay
  # belongs_to :product
  # belongs_to :user

  [:authorized, :captured, :refunded, :error].each do |scoped_key|
    scope scoped_key, -> { where('LOWER(status) = ?', scoped_key.to_s.downcase) }
  end

  class << self
    def process_razorpayment(params)
      issue = Issue.find(params[:product_id])
      razorpay_pmnt_obj = fetch_payment(params[:payment_id])
      status = fetch_payment(params[:payment_id]).status
      if status == "authorized"
        razorpay_pmnt_obj.capture({amount: issue.price * 100})
        razorpay_pmnt_obj = fetch_payment(params[:payment_id])
        params.merge!({status: razorpay_pmnt_obj.status, price: issue.price * 100})
        Order.create(params)
      else
        raise StandardError, "UNable to capture payment"
      end
    end

    def process_refund(payment_id)
      fetch_payment(payment_id).refund
      record = Order.find_by_payment_id(payment_id)
      record.update_attributes(status: fetch_payment(payment_id).status)
      return record
    end

    def filter(params)
      scope = params[:status] ? Order.send(params[:status]) : Order.authorized
      return scope
    end
  end
end

app/models/request.rb
class Request < ApplicationRecord
  validates :name, presence: true
end

app/models/request_gift_log.rb
class RequestGiftLog < ApplicationRecord
  def self.create_log(request_id, gift_id, status=0)
    RequestGiftLog.create(request_id: request_id, gift_id: gift_id, status: status)
  end

  def self.status_update(log)
    if log.status == 0
      log.update(status: 1)
    else
      log.update(status: 0)
    end
    
  end
end

app/models/substance.rb
class Substance < ApplicationRecord
  belongs_to :gift
end

app/models/treatment.rb
class Treatment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_correct_ip, only: [:confirmation]
  def index
    # @microposts_treatment = Micropost.treatment
    # @microposts_survivor = Micropost.suvivor
    @microposts = Micropost.all.order('created_at DESC')
    @applause_num = Applause.all.count
    @donation_amount = Order.where(status: 'captured').sum(:price) / 100
    @donation_count = (DonationLog.all.count / 2).floor
    @treatment_amount = Treatment.sum(:amount)

    @applause = Applause.new
    @donation = Donation.new
    @treatment = Treatment.new

    @issues = Issue.all
    @issue = Issue.new
  end

  def thankyou
  end

  def confirmation
  end

  def calendar
    
  end

  private
    def check_correct_ip
      @issue = Issue.find(params[:id])
      unless @issue.remote_ip == request.remote_ip
        redirect_to root_path
      end
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/applause_helper.rb
module ApplauseHelper
end

app/helpers/donation_helper.rb
module DonationHelper
end

app/helpers/gift_helper.rb
module GiftHelper
  def requested?(gift)
    return !!RequestGiftLog.find_by(gift_id: gift.id)
  end

  def gift_name(gift_id)
    Gift.find(gift_id).substance.name
  end
  def gift_price(gift_id)
    Gift.find(gift_id).substance.price
  end
  def gift_date(gift_id)
    Gift.find(gift_id).date
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issue_helper.rb
module IssueHelper
end

app/helpers/micropost_helper.rb
module MicropostHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/home/calendar.html.erb
<div class="container">
<%= month_calendar do |date| %>
  <%= date %>
<% end %>
</div>

app/views/home/confirmation.html.erb
<div class="container" align="center">
  <div class="confirmation-wrapper">
    <div style="font-size: 20px;">Are you sure to donate Rs. <%= @issue.price %> ? </div>
    <br>
    <br>
    <form action="/purchase" method="POST">
    <script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="rzp_test_wCMDwGpNaYQL4u"

        data-amount="<%= "#{@issue.price * 100}" %>"
        data-name="Contribute for patients"
        data-description="You can contribute directry."

        data-prefill.name="testname"
        data-theme.color="#F37254"
    >
    </script>
      <input type="hidden" value="<%= "#{@issue.id}" %>" name="product_id">
    </form>
  </div>
</div>

<style>
.confirmation-wrapper {
  padding-top: 30px;
}
.razorpay-payment-button {
  background-color: #4CAF50;
  color: white;
  padding: 15px 20px;
  border: none;
  cursor: pointer;
  display: inline-block;
  text-align: center;
  margin-top: 20px;
  min-width: 222px;
}
.razorpay-payment-button:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19); 
}
</style>

app/views/home/index.html.erb
<div class="bg">
  <!-- <div class="mail_title">Why don't you save a life on your special day?</div> -->
  <div class="mail_title">Save a life.</div>
  <!-- <div class="main_data">₹. <span class="main_number"><%= @donation_amount.to_s(:delimited) %></span> raised</div> -->
  <div class="main_data">₹. <span class="main_number"><%= @donation_count %></span> contributes now!</div>
  <!-- <div class="main_data">We have created <span class="main_number"><%= @treatment_amount.to_s(:delimited) %></span> treatments</div> -->
  <div class="main_data"><span class="main_number"><%= @applause_num.to_s(:delimited) %></span> applauses now!</div>
  
  <div class="button-field">
    <button type="button" class="button1"data-toggle="modal" data-target="#applauseModal">
      Applause now! (Free)
    </button>
  </div>

  <div class="button-field">
<!--     <%= link_to '/calendar' do %>    
    <button class="button1">See contribute calendar</button>
    <% end %> -->
    <%= render 'layouts/contributebtn' %>
  </div>
  <% if user_signed_in? %>
    <br> <br>
    <div align="center">
      <button type="button" class="button_blue" data-toggle="modal" data-target="#editNumber">
        Edit Numbers (Admin Only)
      </button>
    </div>
  <% end %>
</div>

<!-- <div class="home-donate-description" style="background: white;">
  <div class="container">
    <div align="center">
      <h3><b>How to contribute?</b></h3>
    </div>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-4">
        <%= image_tag 'home_image1.jpeg',  style: 'width: 100%;' %>
      </div>
      <div class="col-md-4">
        <%= image_tag 'home_image2.jpeg',  style: 'width: 100%;' %>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div> -->

<div class="container">
  <h4 class="subtitle">Latest Stories</h4>
  <span><%= link_to 'View all', micropost_index_path %></span>
  <div class="row" align="center">
    <% @microposts.first(3).each do |micropost| %>
      <%= render 'layouts/post-box', micropost: micropost %>
    <% end %>
  </div>
</div>

<div class="modal fade" id="editNumber" tabindex="-1" role="dialog" aria-labelledby="editNumberLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editNumberLabel">Edit Numbers</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <%= form_for(@donation, url: add_donation_path )do |f| %>
            <label>Add Donation:</label>
            <%= f.number_field :amount , class: 'form-control' %> <br>
            <%= f.submit "Add", class: "btn-sm btn-primary"  %>
          <% end %>
        </div>
        <div class="form-group">
          <%= form_for(@treatment, url: add_treatment_path )do |f| %>
            <label>Add Treatment:</label>
            <%= f.number_field :amount, class: "form-control" %> <br>
            <%= f.submit "Add", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="applauseModal" tabindex="-1" role="dialog" aria-labelledby="applauseModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="applauseModalLabel">Applause</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <div>
            <h6>What's Applause ?</h6>
            <span>You can express your feelings of support for free by applauses.</span> <br>
            <span>You can also attach a message to it.</span> <br>
            <span>Patients can see it.</span>
          </div>
          <%= form_tag(applause_create_path, method: :post) do %> 
            <textarea name="comment" class="form-control" placeholder="Let's cheer!"></textarea>
            <br>
            <div align="center">
              <%= submit_tag 'Applause', class: 'button_blue_sm' %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="contributeModal" tabindex="-1" role="dialog" aria-labelledby="contributeModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="contributeModalLabel">Check it</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          The donation system is in the HP of Indian Cancer Society. You are going to redirect to HP and find forms there. <br> <br>
          In "Purpose of donation", please check <b>Cancer Treatment</b>. Then you can contribute to it. <br>
          <div>
            <%= image_tag 'donate-description.png', class: 'donate-description' %>
          </div>
        </div>
        <div style="text-align: center;">
          <a href="http://www.indiancancersociety.org/how-you-can-help/donate.aspx" target="blank"><button class="button1-sm">OK</button></a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<style type="text/css">
.mail_title {
  font-size: 60px;
  text-align: center;
  color: white;
  font-style: italic;
  padding-top: 80px;
}

.bg {
  background-image: url(<%= asset_path "home-background2.jpg" %>);
  min-height: 820px; 
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  font-family: 'lato';
  line-height: 1.3;
}

.main_data {
  font-size: 35px;
  text-align: center;
  color: white;
}
.main_number {
  font-size: 70px;
  font-style: italic;
}
.button-field {
  padding-top: 40px;
  text-align: center;
}

.post-box:hover {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}

.subtitle {
  margin-top: 60px;
  margin-bottom: 12px;
}

.home-donate-description {
  padding-top: 40px;
  padding-bottom: 80px;
}

@media screen and ( max-width:479px )
{
  .mail_title {
    font-size: 30px;
    text-align: center;
    color: white;
    font-style: italic;
    padding-top: 25px;
  }
  .bg {
    background-image: url(<%= asset_path "home-background2.jpg" %>);
    min-height: 500px; 
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }
  .main_number {
    font-size: 40px;
    font-style: italic;
  }
  .main_data {
    font-size: 30px;
    text-align: center;
    color: white;
  }
}
</style>

app/views/home/thankyou.html.erb
<div class="container" align="center">
  <div class="thankyou-body">
    Thank you for your contribution! <br>
    We will use all the funds you raised for treatments of patients. <br> <br>
    <div class="thankyou-coname">Indian Cancer Society Cancer Cure Fund</div>
    <br><br>
  </div>
  <%= link_to 'Home', root_path %>
</div>

<style>
  .thankyou-body {
    margin-top: 40px;
    font-size: 20px;
  }
  .thankyou-coname {
    font-size: 16px;
  }
</style>