config/routes.rb
Rails.application.routes.draw do
  resources :micropost

  devise_for :users
    as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'
  get 'redirect_to_donate', to: 'donation#create_log', as: 'redirect_to_donate'

  post 'applause', to: 'applause#create', as: 'applause_create'
  post 'donation', to: 'donation#add_donation', as: 'add_donation'
  post 'treatment', to: 'treatment#add_treatment', as: 'add_treatment'
  
  post '/purchase' => 'orders#purchase_status'
  get "refund/:id", to: "orders#refund"

  get 'thankyou', to: 'home#thankyou', as: 'thankyou'
  get 'confirmation', to: 'home#confirmation', as: 'confirmation'
  # get 'calendar', to: 'home#calendar', as: 'calendar'

  resources :issue, only: [:create]

  get 'gift/:date', to: 'gift#show', as: 'gift_of'
  post 'gift_order', to: 'gift#order', as: 'gift_order'

  get 'admin_home', to: 'admin#home', as: 'admin_home'
  get 'admin_status_update', to: 'admin#status_update', as: 'status_update'
end

app/models/applause.rb
class Applause < ApplicationRecord
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/models/donation_log.rb
class DonationLog < ApplicationRecord
end

app/models/gift.rb
class Gift < ApplicationRecord
  has_one :substance
end

app/models/issue.rb
class Issue < ApplicationRecord
  validates :price, presence: true
  validates :price, numericality: { other_than: 0 }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  mount_uploader :image, ImageUploader
  enum status: { treatment: 0, suvivor: 1 }
end

app/models/micropost_log.rb
class MicropostLog < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  include OrderConcerns::Razorpay
  # belongs_to :product
  # belongs_to :user

  [:authorized, :captured, :refunded, :error].each do |scoped_key|
    scope scoped_key, -> { where('LOWER(status) = ?', scoped_key.to_s.downcase) }
  end

  class << self
    def process_razorpayment(params)
      issue = Issue.find(params[:product_id])
      razorpay_pmnt_obj = fetch_payment(params[:payment_id])
      status = fetch_payment(params[:payment_id]).status
      if status == "authorized"
        razorpay_pmnt_obj.capture({amount: issue.price * 100})
        razorpay_pmnt_obj = fetch_payment(params[:payment_id])
        params.merge!({status: razorpay_pmnt_obj.status, price: issue.price * 100})
        Order.create(params)
      else
        raise StandardError, "UNable to capture payment"
      end
    end

    def process_refund(payment_id)
      fetch_payment(payment_id).refund
      record = Order.find_by_payment_id(payment_id)
      record.update_attributes(status: fetch_payment(payment_id).status)
      return record
    end

    def filter(params)
      scope = params[:status] ? Order.send(params[:status]) : Order.authorized
      return scope
    end
  end
end

app/models/request.rb
class Request < ApplicationRecord
  validates :name, presence: true
end

app/models/request_gift_log.rb
class RequestGiftLog < ApplicationRecord
  def self.create_log(request_id, gift_id, status=0)
    RequestGiftLog.create(request_id: request_id, gift_id: gift_id, status: status)
  end

  def self.status_update(log)
    if log.status == 0
      log.update(status: 1)
    else
      log.update(status: 0)
    end
    
  end
end

app/models/substance.rb
class Substance < ApplicationRecord
  belongs_to :gift
end

app/models/treatment.rb
class Treatment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/micropost_controller.rb
class MicropostController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update]

  def index
    if params[:status]
      @microposts = Micropost.where(status: params[:status])
    else
      @microposts = Micropost.all
    end
  end

  def new
    @micropost = Micropost.new
  end

  def show
    @micropost = Micropost.find(params[:id])
    MicropostLog.create(micropost_id: @micropost.id)
    # @issues = Issue.all
    # @issue = Issue.new
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def update
    @micropost = Micropost.find(params[:id])
    if @micropost.update_attributes(micropost_params)
      redirect_to @micropost
    else
      render action: :edit
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy
    redirect_to root_path
  end

  def create
    @micropost = Micropost.new(micropost_params)
    if @micropost.save
      redirect_to @micropost
    else
      render action: :new
    end
  end

  private
    def micropost_params
      params.require(:micropost).permit(:name, :title, :content, :image, :status, :plain_content)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/applause_helper.rb
module ApplauseHelper
end

app/helpers/donation_helper.rb
module DonationHelper
end

app/helpers/gift_helper.rb
module GiftHelper
  def requested?(gift)
    return !!RequestGiftLog.find_by(gift_id: gift.id)
  end

  def gift_name(gift_id)
    Gift.find(gift_id).substance.name
  end
  def gift_price(gift_id)
    Gift.find(gift_id).substance.price
  end
  def gift_date(gift_id)
    Gift.find(gift_id).date
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issue_helper.rb
module IssueHelper
end

app/helpers/micropost_helper.rb
module MicropostHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/treatment_helper.rb
module TreatmentHelper
end

app/views/micropost/edit.html.erb
<div class="container">
<%= form_for(@micropost, url: {action: 'update'}, :html => { :multipart => true }) do |f| %>
  <% if @micropost.errors.any? %>
    <h4>入力した内容にエラーが<%= @micropost.errors.count %>件あります</h4>
    <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  
    <div>
      <table class="table">
        <tbody>
          <tr>
            <th>Image</th>
              <td>
                <%= f.file_field :image %>
                <%= f.hidden_field :image_cache %>
              </td>
          </tr>
          <tr>
            <th>Status</th>
            <td>
              <%= f.select :status, Micropost.statuses.keys.to_a, {} %>
            </td>
          </tr>
          <tr>
            <th>Name</th>
            <td><%= f.text_field :name, placeholder: "Fullname", class: 'form-control input-sm'  %></td>
          </tr>
          <tr>
            <th>Title of this post</th>
            <td><%= f.text_field :title, placeholder: "Title of this post", class: 'form-control input-sm'  %></td>
          </tr>
          <tr>
            <th>Content</th>
              <td>
                <div id='editor'>
                  <%= f.text_area :content, placeholder: "Content...", class: 'form-control input-sm', style: 'height: 500px;' %>  
                  </div>
                </div>
              </td>
          </tr>
          <tr>
            <th>Plain content</th>
            <td><%= f.text_area :plain_content, placeholder: "Do not use markdown. This is the plain text for some descriptions.", class: 'form-control input-sm', style: 'height: 500px;' %></td>
          </tr>
        </tbody>
      </table>
    <div style="text-align: center;">
      <%= f.submit "Update", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/micropost/index.html.erb
<div class="container">
<div class="row" align="center">
  <% @microposts.each do |micropost| %>
    <%= render 'layouts/post-box', micropost: micropost %>
  <% end %>
</div>
</div>

app/views/micropost/new.html.erb
<div class="container">
<%= form_for(@micropost, url: {action: 'create'}, :html => { :multipart => true }) do |f| %>
  <% if @micropost.errors.any? %>
    <h4>入力した内容にエラーが<%= @micropost.errors.count %>件あります</h4>
    <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  
    <div>
      <table class="table">
        <tbody>
          <tr>
            <th>Image</th>
              <td>
                <%= f.file_field :image %>
                <%= f.hidden_field :image_cache %>
              </td>
          </tr>
          <tr>
            <th>Status</th>
            <td>
              <%= f.select :status, Micropost.statuses.keys.to_a, {} %>
            </td>
          </tr>
          <tr>
            <th>Name</th>
            <td><%= f.text_field :name, placeholder: "Fullname", class: 'form-control input-sm'  %></td>
          </tr>
          <tr>
            <th>Title of this post</th>
            <td><%= f.text_field :title, placeholder: "Title of this post", class: 'form-control input-sm'  %></td>
          </tr>
          <tr>
            <th>Content</th>
            <td><%= f.text_area :content, placeholder: "Content...", class: 'form-control input-sm', style: 'height: 500px;' %></td>
          </tr>
          <tr>
            <th>Plain content</th>
            <td><%= f.text_area :plain_content, placeholder: "Do not use markdown. This is the plain text for some descriptions.", class: 'form-control input-sm', style: 'height: 500px;' %></td>
          </tr>
        </tbody>
      </table>
    <div style="text-align: center;">
      <%= f.submit "Create", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/micropost/show.html.erb
<div class="container">
  <div class="field">
    <h1 class="micropost-title">
      <%= @micropost.title %>
    </h1>
    <div>
      <b>Share</b><%= social_share_button_tag(@micropost.title, desc: @micropost.plain_content) %>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <div class="profile-image" align="center">
          
          <% if @micropost.image? %>
            <%= image_tag @micropost.image_url(:thumb) %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="post-header-intro">
          <div class="patient-name"><%= @micropost.name %></div>
          <div>
            <% if @micropost.status == 'treatment' %>
              Under treatment
            <% else %>  
              Cancer survivor
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row content">
      <div class="col-md-8">
        <%= qiita_markdown(@micropost.content) %>
        <br>
<!--     <%= link_to '/calendar' do %>    
    <button class="button1">See contribute calendar</button>
    <% end %> -->
    <%= render 'layouts/contributebtn' %>
      </div>
      <div class="col-md-4"></div>
    </div>
    <% if user_signed_in? %>
    <tr>
      <th>Links</th>
      <td>
        <%= link_to 'Edit', edit_micropost_path %> <br>
        <%= link_to 'Back', root_path %> <br>
        <%= link_to 'Delete', micropost_path(@micropost), method: :delete %> <br>
        
      </td>
    </tr>
    <% end %>
  </div>
</div>

<style>
.profile-image img {
  width: 200px;
  height: 200px;
  object-fit: cover;
  background-color: #ccc;
  border: 1px solid #ccc;
}
.field {
  background-color: white;
  padding: 30px 100px;
}
.micropost-title {
  font-size: 36px;
  text-align: center;
  margin-bottom: 20px;
}
.content {
  margin-top: 40px;
}
table tbody td {
  max-width: 100%;
  word-wrap: break-word;
}

table td, table th {
  display: block;
  width: 100%;
}
.patient-name {
  font-size: 20px;
}
@media screen and ( max-width:479px )
{
  .field {
    background-color: white;
    padding: 10px 7px;
  }
  .post-contribute-btn {
    text-align: center;
    margin-top: 10px;
  }
  .post-header-intro {
    text-align: center;
    margin-top: 10px;
  }
}
</style>